---
title: "To Do List"
output: html_document
---

# Literature Review

:white_large_square: Definir flujo de trabajo, esquema yed o similar - en Dropbox

~~Leer artículos similares~~ ver Google doc para verlos

~~Definir criterio de búsqueda (Time-span: 1970-2016, Query: TS=(Sierra Nevada* AND (Spain* OR España*))~~

:wavy_dash: Comprobar número y relevancia de publicaciones anteriores a 1970 (Regino): Documentado en “Search in WoS”

:white_large_square: Resolver basic Incidences

    - Incoherences in Title (i.e. title not as it appears in the paper, differences between tables, languages...) 
    
    - Incoherences in author (i.e. author not as it appears in the paper, differences between tables...)
    
    - Avoiding duplicates
    
    - Languages: some references are in a different language than english and spanish (german and french). Do we consider them? How to avoid duplicates due to translations? Consider that some papers may have parts of them in an accepted language, but not the whole text, or the other way around (i.e. they may appear with english title in WoS even though the paper was published in a different language)

:white_large_square: Estadísticas básicas - cuales? Markdown "Basic Statistics" en la carpeta "Analysis". En conjunto a los datos obtenidos en la encuesta, así como las BD ya existentes.

:white_large_square: Creación de un base de datos que conecte información espacial, refbase, campos nuevos (etiquetas, etc, etc): BD creada en Access para uso preliminar. 

:red_circle: Descarga de pdf: Faltan bastantes, sobre todo por problemas con el acceso/permiso

:white_large_square: Integración en Refbase 

  - Manejo de la herramienta

  ~~-Crear cuenta~~

  - Crear diccionario de etiquetas

  - Utilizar Envthes o algún vocabulario controlado?

## Controles

- ~~Control interno~~

- Nuestra BD vs WoS

- Encuesta vs WoS

## Georeferenciación

~~Anotar referencias en artículos descargados~~

~~Definir criterios de referenciación~~

See "Sampling References" tab in "AA Papers", and consider also models, geological settings, species&taxonomy based on collections, herbaria,...

Regino's recommendations: include in the database literally what authors say in their paper, if possible just copy pasta what it is said in the methodology. 

  **Note**: careful with sensitive species and how to treat data related to them, make sure what international law and the Park says about what can be openly public and what needs to be limited accesible (by experts for example).

Decisión: anotar aquellos que tienen las coordenadas geograficas, los demás se irán viendo según casuíatica. Ver anotaciones en cuaderno (Reunión 25/04/2016).

:white_large_square: Sistematizar anotaciones sobre referencia espacial en una tabla/BD con: id (key?), coordenadas (y tipo de vector (punto, línea, polígono)), topónimo, incertidumbre... - Base de datos PostgreSQL-PostGIS

~~Aprender a manejar información espacial QGIS~~
http://www.qgis.org/es/site/ IN PROCESS

:white_large_square: Preparar qGIS: mapa de SN

:white_large_square: Espacialización de la información generada

- Temporal aspect

~~Basically the conflict here is to decide what is considered for the study. For example, if a sample is taken at a certain point in time and space, is it that what we include? It seems simple but the variety of spatial and temporal ranges studies makes it a bit more complex...~~ 

Decisión: referir sólo al año de muestreo (y al rango temporal, si se quisiera). 

## Data Mining

:white_large_square: Learning data mining, exploring package, text mining visualization, VOSviewer or alternatives (Plotly+Rshiny)...

:wavy_dash: Table Areas_x_Journal: 

  :heavy_check_mark: Categories list
  
  :heavy_check_mark: Journal list per science category
  
  :heavy_check_mark: Journal list per social science category
  
  :white_large_square: build database relating Categories & Journals: started, need to transform the Journal lists to be able to include them


:white_large_square: Define topics for expert criteria analysis: hierarchical vs "key words", both cases,...

Algunos recursos interesantes en R:
An introduction to text mining in R. R News, 8(2):19–22, Oct. 2008. URL http://CRAN.R-project. org/doc/Rnews/.
paquetes: 
- koRpus: útil para el análisis de frecuencias
- tm 
Algún test hecho para estos paquetes, en "/analysis/Frequency_analysis"

vignettes:
http://handsondatascience.com/TextMiningO.pdf 
https://rstudio-pubs-static.s3.amazonaws.com/31867_8236987cf0a8444e962ccd2aec46d9c3.html 
http://www.cs.ukzn.ac.za/~murrellh/dm/content/slides10.pdf 

Algunas notas sobre Data Mining: 
Term frequency and association analyses are simple but widely used methods in text mining because the results are relatively simple to calculate and interpret (Namey et al., 2007: 141; Ryan and Bernard, 2000: 776).

Ver a este amigacho http://faculty.washington.edu/bmarwick/publications/ 

Notas sobre visualización: bibliometric tools, text mining visualization,...
VOSviewer es una herramienta Java que permite hacer clusters/ontologías basados en relaciones:
Buscar manual
Qué necesita/usa para establecer relaciones?
Investigar alternativas abiertas: shiny, R+plotly...

:white_large_square: Writing methods: To which level of detail? Export process, documentation,...


# Survey

- ~~Hacer y enviar encuesta~~

:white_large_square: Answers analysis: what do we want to extract from the answers?
  Main topics
  Time of research
  Publications: used for control with WoS search 
  
      - Do we consider non per-reviewed publications? In that case, caution should prevail since researchers were actually asked for "scientific publications"
  Problems
  
:white_large_square: Merge with Search, to integrate together authors, topics, as control of the search
  
:white_large_square: Contestar correos Tinaut, Noriega...
