---
title: "Table filename_title"
output: html_document
---

```{r}

library("stringr")
library("tidyr")

di <- paste(machine, "/Dropbox/Review_Sierra_Nevada/sngc_review", sep = "")

# Making a table with all citations
files <- list.files(path = paste(di, "/data/wos_raw/", sep= ""), pattern= "\\.txt$")

for (j in files){ 
   aux <- read.csv(file=paste(di, "/data/wos_raw/", j, sep= ""),
               header = TRUE,
               sep = '\t')
   name_aux <- str_replace(j, "\\..*", "") 
   
   assign(name_aux, aux)
   }

rawdf <- rbind(bioCI, bioP, med, wos1, wos2, zoo)
View(rawdf)

# Add columns for first author and author address
d <- rawdf[, c("Authors..Primary", "Author.Address")]
names(d) <- c("authors", "address")

#Create as many columns as authors
max_columnas <- max(stringr::str_count(d$authors, pattern=";"))
vec_columnas <- paste0("a", 1:(max_columnas + 1))

# Fill such columns with the authors, each in one column
all_authors_colum <- tidyr::separate(d, authors, into=vec_columnas, extra="merge", sep=";")
View(all_authors_colum)
```

Now we want to create a table with first author, title and year
```{r}
# Create a column with the first author only in the complete table
rawdf$first_author<-all_authors_colum$a1

# create a data frame with title, first author and year only
all_selected<-data.frame(rawdf$Title.Primary,rawdf$first_author,rawdf$Pub.Year)
```

Now we need to find the way of merging this table (all_selected) with Libro1 in the right rows (merging title with title)



titles_lacking<-read.csv("Libro1.csv")

titles_lacking <- read.table("Libro1.txt", sep=" ", header=TRUE)
merge(x=all_authors_colum$a1,y=)